"""
Streamlit Interactive Dashboard
===============================
Provides an interactive web interface for visualizing clusters 
and anomalies generated by the Unsupervised Learning pipeline.
"""

import os
import pandas as pd
import numpy as np
import plotly.express as px
import streamlit as st

# Setup absolute paths to handle Streamlit execution context
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
PROCESSED_DATA_PATH = os.path.join(PROJECT_ROOT, "data", "processed", "online_retail_clustered.csv")
RAW_DATA_PATH = os.path.join(PROJECT_ROOT, "data", "processed", "online_retail_processed.csv")
PROFILE_DATA_PATH = os.path.join(PROJECT_ROOT, "artifacts", "cluster_profiles.csv")

st.set_page_config(page_title="Customer Segmentation Dashboard", layout="wide")

@st.cache_data
def load_data():
    """Loads and caches required dataframes."""
    # 1. Scaled/Reduced PCA data with Cluster assignments
    df_pca = pd.read_csv(PROCESSED_DATA_PATH)
    
    # 2. Raw unscaled data
    df_raw = pd.read_csv(RAW_DATA_PATH)
    
    # 3. Cluster Summary Profiles
    df_profiles = pd.read_csv(PROFILE_DATA_PATH)
    
    return df_pca, df_raw, df_profiles

st.title("🛒 E-Commerce Customer Segmentation & Anomaly Detection")

# Check if data exists
if not os.path.exists(PROCESSED_DATA_PATH):
    st.error("Error: Clustering Data not found! Please run the pipeline first.")
    st.stop()

# --- Load Data ---
df_pca, df_raw, df_profiles = load_data()


# -------------------------------
# TAB NAVIGATION
# -------------------------------
tab1, tab2, tab3 = st.tabs(["🚀 Overview & PCA Embeddings", "📊 Cluster Profiles", "🚨 Anomaly Detection"])


# -------------- TAB 1: PCA ---------------
with tab1:
    st.header("Behavioral Embeddings (PCA Space)")
    st.markdown("We compressed 15 customer behaviors into a high-density 2-D space to visualize natural clustering.")
    
    # Since dataset is large (400k+), we can downsample merely for UI plotting speed
    sample_size = st.slider("Plot Sample Size (To prevent browser lag)", min_value=1000, max_value=50000, value=5000, step=1000)
    df_plot = df_pca.sample(n=sample_size, random_state=42)
    
    df_plot["Cluster"] = df_plot["Cluster_KMeans"].astype(str)
    
    # Optional 3D checkbox
    show_3d = st.checkbox("Show as 3D Scatter")
    if show_3d:
        fig_pca = px.scatter_3d(
            df_plot, x="PC1", y="PC2", z="PC3", 
            color="Cluster", opacity=0.7, height=700,
            title="3D Principal Component Scatter"
        )
    else:
        fig_pca = px.scatter(
            df_plot, x="PC1", y="PC2", 
            color="Cluster", opacity=0.6, height=600,
            title="2D Principal Component Scatter"
        )
    
    fig_pca.update_traces(marker=dict(size=4))
    st.plotly_chart(fig_pca, use_container_width=True)


# -------------- TAB 2: PROFILES ---------------
with tab2:
    st.header("Customer Segments & Business Value")
    
    # Top Level Metrics
    total_customers = df_profiles['Customer_Count'].sum()
    total_txns = df_profiles['Transaction_Count'].sum()
    
    col1, col2 = st.columns(2)
    col1.metric("Total Unique Customers", f"{total_customers:,}")
    col2.metric("Total Transactions", f"{total_txns:,}")
    
    st.subheader("Cluster Profile Statistics (Median)")
    
    # Display styled dataframe
    st.dataframe(df_profiles.style.format(
        {"TotalPrice": "${:,.2f}", "avg_purchase_value": "${:,.2f}"}
    ), use_container_width=True)
    
    st.divider()
    
    # Visualize Spends
    st.subheader("Average Spend per Transaction by Cluster")
    fig_bar = px.bar(df_profiles, x="Cluster_Profile", y="TotalPrice", color="Cluster_Profile",
                     text="TotalPrice", labels={"TotalPrice": "Median Transaction Value ($)"})
    fig_bar.update_traces(texttemplate='$%{text:.2s}', textposition='outside')
    st.plotly_chart(fig_bar, use_container_width=True)


# -------------- TAB 3: ANOMALIES ---------------
with tab3:
    st.header("Fraud & Extreme Outlier Detection")
    st.markdown("We isolated Extreme buyers or highly unusual activity patterns utilizing **Isolation Forests.**")
    
    if "Is_Anomaly_IForest" not in df_pca.columns:
        st.warning("Anomaly labels not found. Ensure you ran `anomaly_models.py`")
    else:
        num_anomalies = (df_pca["Is_Anomaly_IForest"] == -1).sum()
        num_normal = (df_pca["Is_Anomaly_IForest"] == 1).sum()
        
        col1, col2 = st.columns(2)
        col1.metric("Normal Traffic", f"{num_normal:,}")
        col2.metric("Flagged Anomalies (-1)", f"{num_anomalies:,}")
        
        # Subsample for Anomaly Plotting
        df_anom_plot = df_pca.sample(n=sample_size, random_state=42)
        df_anom_plot["Status"] = df_anom_plot["Is_Anomaly_IForest"].map({1: "Normal", -1: "Anomaly"})
        
        fig_anom = px.scatter(
            df_anom_plot, x="PC1", y="PC2", 
            color="Status", 
            color_discrete_map={"Normal": "#A2D5F2", "Anomaly": "#E63946"},
            opacity=0.6, height=600,
            title="Isolation Forest Scatter (Normal vs Anomaly)"
        )
        st.plotly_chart(fig_anom, use_container_width=True)
        
        st.subheader("Outlier Score Distribution")
        fig_hist = px.histogram(
            df_pca.sample(n=sample_size, random_state=42), 
            x="Anomaly_Score_IForest", 
            nbins=40, color_discrete_sequence=["#9B5DE5"],
            title="Density Distribution of Anomaly Scores (Negative = Outlier)"
        )
        st.plotly_chart(fig_hist, use_container_width=True)
